import { env } from "cloudflare:test";

const CURRENT_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS orders (
    tenant_id TEXT NOT NULL,
    order_id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    channel TEXT NOT NULL DEFAULT 'telegram',
    product_type TEXT NOT NULL,
    telegram_chat_id TEXT,
    amount_in_cents INTEGER,
    wallet_address TEXT,
    current_step TEXT NOT NULL DEFAULT 'draft',
    status TEXT NOT NULL DEFAULT 'draft',
    split_address TEXT,
    split_fee TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  "CREATE INDEX IF NOT EXISTS orders_user_id_idx ON orders (user_id)",
  "CREATE INDEX IF NOT EXISTS orders_status_idx ON orders (status)",
  "CREATE INDEX IF NOT EXISTS orders_tenant_id_idx ON orders (tenant_id)",
  "CREATE INDEX IF NOT EXISTS orders_tenant_user_channel_chat_idx ON orders (tenant_id, user_id, channel, telegram_chat_id)",
  `CREATE TABLE IF NOT EXISTS deposits (
    tenant_id TEXT NOT NULL,
    deposit_entry_id TEXT PRIMARY KEY NOT NULL,
    qr_id TEXT,
    order_id TEXT NOT NULL,
    nonce TEXT NOT NULL,
    qr_copy_paste TEXT NOT NULL,
    qr_image_url TEXT NOT NULL,
    external_status TEXT NOT NULL DEFAULT 'pending',
    expiration TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE
  )`,
  "CREATE INDEX IF NOT EXISTS deposits_order_id_idx ON deposits (order_id)",
  "CREATE INDEX IF NOT EXISTS deposits_external_status_idx ON deposits (external_status)",
  "CREATE UNIQUE INDEX IF NOT EXISTS deposits_qr_id_unique_idx ON deposits (qr_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS deposits_nonce_unique_idx ON deposits (nonce)",
  "CREATE INDEX IF NOT EXISTS deposits_tenant_id_idx ON deposits (tenant_id)",
  "CREATE INDEX IF NOT EXISTS deposits_tenant_order_idx ON deposits (tenant_id, order_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS deposits_tenant_order_unique_idx ON deposits (tenant_id, order_id)",
  "CREATE INDEX IF NOT EXISTS deposits_tenant_qr_idx ON deposits (tenant_id, qr_id)",
  `CREATE TABLE IF NOT EXISTS scheduled_deposit_reconciliation_claims (
    tenant_id TEXT NOT NULL,
    deposit_entry_id TEXT NOT NULL,
    claimed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tenant_id, deposit_entry_id),
    FOREIGN KEY (deposit_entry_id) REFERENCES deposits(deposit_entry_id) ON DELETE CASCADE
  )`,
  "CREATE INDEX IF NOT EXISTS scheduled_deposit_reconciliation_claims_claimed_at_idx ON scheduled_deposit_reconciliation_claims (claimed_at)",
  `CREATE TABLE IF NOT EXISTS deposit_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    tenant_id TEXT NOT NULL,
    order_id TEXT NOT NULL,
    deposit_entry_id TEXT NOT NULL,
    qr_id TEXT,
    source TEXT NOT NULL,
    external_status TEXT NOT NULL,
    bank_tx_id TEXT,
    blockchain_tx_id TEXT,
    raw_payload TEXT NOT NULL,
    received_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    FOREIGN KEY (deposit_entry_id) REFERENCES deposits(deposit_entry_id) ON DELETE CASCADE
  )`,
  "CREATE INDEX IF NOT EXISTS deposit_events_order_id_idx ON deposit_events (order_id)",
  "CREATE INDEX IF NOT EXISTS deposit_events_deposit_entry_id_idx ON deposit_events (deposit_entry_id)",
  "CREATE INDEX IF NOT EXISTS deposit_events_qr_id_idx ON deposit_events (qr_id)",
  "CREATE INDEX IF NOT EXISTS deposit_events_source_idx ON deposit_events (source)",
  "CREATE INDEX IF NOT EXISTS deposit_events_tenant_id_idx ON deposit_events (tenant_id)",
  "CREATE INDEX IF NOT EXISTS deposit_events_tenant_deposit_entry_idx ON deposit_events (tenant_id, deposit_entry_id)",
  "CREATE INDEX IF NOT EXISTS deposit_events_tenant_qr_idx ON deposit_events (tenant_id, qr_id)",
  `CREATE UNIQUE INDEX IF NOT EXISTS deposit_events_idempotency_unique_idx ON deposit_events (
    tenant_id,
    deposit_entry_id,
    IFNULL(qr_id, ''),
    source,
    external_status,
    IFNULL(bank_tx_id, ''),
    IFNULL(blockchain_tx_id, ''),
    raw_payload
  )`,
  `CREATE TABLE IF NOT EXISTS deposit_order_duplicate_quarantine (
    tenant_id TEXT NOT NULL,
    order_id TEXT NOT NULL,
    deposit_entry_id TEXT PRIMARY KEY NOT NULL,
    qr_id TEXT,
    nonce TEXT NOT NULL,
    qr_copy_paste TEXT NOT NULL,
    qr_image_url TEXT NOT NULL,
    external_status TEXT NOT NULL,
    expiration TEXT,
    original_created_at TEXT NOT NULL,
    original_updated_at TEXT NOT NULL,
    quarantined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    canonical_deposit_entry_id TEXT NOT NULL,
    quarantine_reason TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS deposit_order_duplicate_event_quarantine (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    original_event_id INTEGER NOT NULL,
    tenant_id TEXT NOT NULL,
    order_id TEXT NOT NULL,
    deposit_entry_id TEXT NOT NULL,
    qr_id TEXT,
    source TEXT NOT NULL,
    external_status TEXT NOT NULL,
    bank_tx_id TEXT,
    blockchain_tx_id TEXT,
    raw_payload TEXT NOT NULL,
    original_received_at TEXT NOT NULL,
    quarantined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    canonical_deposit_entry_id TEXT NOT NULL,
    quarantine_reason TEXT NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS deposit_order_duplicate_quarantine_tenant_order_idx ON deposit_order_duplicate_quarantine (tenant_id, order_id)",
  "CREATE INDEX IF NOT EXISTS deposit_order_duplicate_event_quarantine_tenant_order_idx ON deposit_order_duplicate_event_quarantine (tenant_id, order_id)",
];

export async function resetDatabaseSchema() {
  const resetStatements = [
    "DROP TABLE IF EXISTS deposit_order_duplicate_event_quarantine",
    "DROP TABLE IF EXISTS deposit_order_duplicate_quarantine",
    "DROP TABLE IF EXISTS deposit_events",
    "DROP TABLE IF EXISTS scheduled_deposit_reconciliation_claims",
    "DROP TABLE IF EXISTS deposits",
    "DROP TABLE IF EXISTS orders",
    ...CURRENT_SCHEMA_STATEMENTS,
  ];

  await env.DB.batch(resetStatements.map((statement) => env.DB.prepare(statement)));
}
